### ISSUE TITLE
NPE optional array

### ISSUE THREAD

**Issue by UshakovVasilii** [aichaos/rivescript-java#20]
RS file:

```
! version = 2.0

+ [(a|b) ](c|d)
- <star2>
```

input `c`

```
java.lang.NullPointerException
    at com.rivescript.Util.Sv2s(Util.java:52) ~[rivescript-core-0.7.0-SNAPSHOT.jar:?]
    at com.rivescript.RiveScript.processTags(RiveScript.java:1690) ~[rivescript-core-0.7.0-SNAPSHOT.jar:?]
    at com.rivescript.RiveScript.reply(RiveScript.java:1511) ~[rivescript-core-0.7.0-SNAPSHOT.jar:?]
    at com.rivescript.RiveScript.reply(RiveScript.java:1062) ~[rivescript-core-0.7.0-SNAPSHOT.jar:?]
```

**Comment by marceloverdijk** [comment]
Instead of adding a `null` star to the array, we now add an empty String `""`.
